name: Code Quality

on:
    push:
        branches: [main]

jobs:
    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: Install Dependencies
              run: npm install --legacy-peer-deps

              #Check Linting

            - name: Lint Check
              run: npm run lint

            #Security Check

            - name: Code Security Audit
              run: npm audit --audit-level=high

        
            #Build Check

            - name: Build App
              run: npm run build
